/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package from_hd;

import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*import model.Chitet_hdModify;
import model.HoaDonModify;
import model.Product;
import model.ProductModify;
import model.chi_tiet_hd;
import model.quanlyhoadon;*/

/**
 *
 * @author Admin
 */
public class Hoadon extends javax.swing.JFrame {
HoaDonModify a= new HoaDonModify();
    Chitet_hdModify dao= new Chitet_hdModify();
    
    private List<quanlyhoadon> hoadon;
    private List<Product> sanpham;
    //private List<chi_tiet_hd> sanphamct;
   ArrayList<chi_tiet_hd> sanphamct=new ArrayList<>();
    private DefaultTableModel ModelHD;
    private DefaultTableModel ModelSP;
    private DefaultTableModel ModelSPCT;
    int selectedIndex;
    public Hoadon() {
        initComponents();
        ModelHD=(DefaultTableModel) table_hd.getModel();
        ModelSP=(DefaultTableModel) table_sanpham.getModel();
        ModelSPCT=(DefaultTableModel) table_chi_tiet_hd.getModel();
        showTableHD();
        showTableSP();
        showTableSPCT_tamthoi();
        showTableSPCT_themmoi();
        
    }
    //hiển thị bảng hóa đơn
    private void showTableHD(){
        hoadon=new HoaDonModify().getListHD();
        ModelHD.setRowCount(0);
        for(quanlyhoadon hd:hoadon){
            ModelHD.addRow(new Object[]{
                hd.getMahd(),hd.getSdt_kh(),hd.getDate_Buy(),hd.getThanhTien()
            });
            
        }
        
    }
    
    // hiển thị bảng chọn sản phẩm
    private void showTableSP(){
        sanpham=new ProductModify().getProduct();
        ModelSP.setRowCount(0);
        for(Product s:sanpham){
            ModelSP.addRow(new Object[]{
                s.getMa_sp(),s.getTen_sp(),s.getGia_ban(),s.getSo_luong()
            });
        }
        
    }
    //hiển thị bảng chi tiết hóa đơn tạm thời 
    public void showTableSPCT_tamthoi(){
        ModelSPCT.setRowCount(0);
        //ArrayList<chi_tiet_hd> sanphamct=new ArrayList<>();
        for(chi_tiet_hd s:sanphamct)
        {
            Object[] row=new Object[]
            {
                table_chi_tiet_hd.getRowCount()+1,s.getMasp(),s.getSo_luong(),s.getGia_ban(),s.getTong()};
            ModelSPCT.addRow(row);
            }
        
    }
    // hien thi bang chi tiet hoa don tam thoi khi click chon "them moi hoa don"
    public void showTableSPCT_themmoi(){
        sanphamct.clear();
        showTableSPCT_tamthoi();
    }
    public void showTableSPCT(){
    int ma_hd=0;
    sanphamct=new Chitet_hdModify().getchi_tiet_hdByMa_hd(ma_hd);
        ModelSPCT.setRowCount(0);
        //ArrayList<chi_tiet_hd> sanphamct=new ArrayList<>();
        for(chi_tiet_hd s:sanphamct)
        {
            Object[] row=new Object[]
            {
                table_chi_tiet_hd.getRowCount()+1,s.getMasp(),s.getSo_luong(),s.getGia_ban(),s.getTong()};
            ModelSPCT.addRow(row);
            }
        
    }
    
    
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTensp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTong = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txt_sdt_khach = new javax.swing.JTextField();
        txtSp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSo_luong = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_sanpham = new javax.swing.JTable();
        btnThanh_toan = new javax.swing.JButton();
        btnXoa_gio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_hd = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_chi_tiet_hd = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        btnAdd_bill = new javax.swing.JButton();
        btnAdd_sp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phiếu mua hàng");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("HÓA ĐƠN");
        jLabel1.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Tên Sản phẩm");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("so dien thoai khach");

        txtTensp.setToolTipText("Tên Sản phẩm");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Mã Sản phẩm");

        txtTong.setToolTipText("Tổng tiền");

        txtGia.setToolTipText("Đơn giá");

        txt_sdt_khach.setToolTipText("Mã nhân viên");

        txtSp.setToolTipText("Mã Sản phẩm");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Số Lượng");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Tổng tiền");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Đơn giá");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_sdt_khach, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSp)
                        .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTong, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSo_luong, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sdt_khach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSo_luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDelete.setText("Xóa hóa đơn");
        btnDelete.setToolTipText("Xóa");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Tìm kiếm");
        jButton2.setToolTipText("Tìm kiếm");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        table_sanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Gía bán", "Số lượng"
            }
        ));
        table_sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_sanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_sanpham);

        btnThanh_toan.setText("Thanh toán");
        btnThanh_toan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanh_toanActionPerformed(evt);
            }
        });

        btnXoa_gio.setText("Xóa hàng trong giỏ");
        btnXoa_gio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_gioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnXoa_gio)
                        .addGap(128, 128, 128)
                        .addComponent(btnDelete)
                        .addGap(30, 30, 30)
                        .addComponent(btnThanh_toan)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThanh_toan)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnXoa_gio)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        table_hd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "sdt khách hàng", "Ngày mua", "Thành tiền"
            }
        ));
        table_hd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_hdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_hd);

        table_chi_tiet_hd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số thứ tự", "Mã sản phẩm", "Số lượng", "Gía bán", "Tổng"
            }
        ));
        table_chi_tiet_hd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_chi_tiet_hdMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_chi_tiet_hd);
        if (table_chi_tiet_hd.getColumnModel().getColumnCount() > 0) {
            table_chi_tiet_hd.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel10.setText("Chi tiết hóa đơn");

        btnAdd_bill.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdd_bill.setText("Thêm hóa đơn");
        btnAdd_bill.setToolTipText("Thêm sản phẩm");
        btnAdd_bill.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));
        btnAdd_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_billActionPerformed(evt);
            }
        });

        btnAdd_sp.setText("Cho vào giỏ");
        btnAdd_sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_spActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(108, 108, 108)
                        .addComponent(btnAdd_bill)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd_sp)
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(670, 670, 670))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnAdd_bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdd_sp))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// thêm hóa đơn
    private void btnAdd_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_billActionPerformed

       showTableSPCT_themmoi();    
    }//GEN-LAST:event_btnAdd_billActionPerformed
//click trong bảng sản phẩm
    private void table_sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_sanphamMouseClicked
        // TODO add your handling code here:
        selectedIndex=table_sanpham.getSelectedRow();
        Product sp=sanpham.get(selectedIndex);
        txtSp.setText(String.valueOf(sp.getMa_sp()));
        txtTensp.setText(sp.getTen_sp());
        txtGia.setText(sp.getGia_ban()+"");
    }//GEN-LAST:event_table_sanphamMouseClicked
// thêm sản phẩm vào giỏ
    private void btnAdd_spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_spActionPerformed
        // TODO add your handling code here:
       int masp=0;
        int soluong=0;
        int gia=0;  
        masp=Integer.parseInt(txtSp.getText());
        soluong=Integer.parseInt(txtSo_luong.getText());
        gia=Integer.parseInt(txtGia.getText());
        int tong=soluong*gia;
        chi_tiet_hd sp=new chi_tiet_hd(masp,soluong,gia,tong);
       sanphamct.add(sp);
        //dao.addSP(sp);
       // dao.Dungtest(GIA);
        showTableSPCT_tamthoi();      
    }//GEN-LAST:event_btnAdd_spActionPerformed
//click vào bảng chi tiết hóa đơn   
    private void table_chi_tiet_hdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_chi_tiet_hdMouseClicked
      
    }//GEN-LAST:event_table_chi_tiet_hdMouseClicked
// đẩy chi tiết hóa đơn lên db
    public void luu_db_chi_tiet_hd(int k){
    for(int i=0;i<sanphamct.size();i++)
    {
         
        int ma_sp=sanphamct.get(i).getMasp();
        int so_luong=sanphamct.get(i).getSo_luong();
        int tong=sanphamct.get(i).getTong();
        chi_tiet_hd sp=new chi_tiet_hd(ma_sp,so_luong,tong );    
        
       dao.addSP(sp,k);
    }
        
}
// lấy ngày tháng tự động    
 public String getdate(){
     DateTimeFormatter dtf = DateTimeFormatter.ofPattern("uuuu/MM/dd HH:mm:ss");
    ZonedDateTime now = ZonedDateTime.now();
    
    String date= dtf.format(now);
    return date;
 }
// thanh toán
    private void btnThanh_toanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanh_toanActionPerformed
        // tự động reset các ô nhập
        txtSp.setText("");
        txtTensp.setText("");
        txtSo_luong.setText("");
        txtGia.setText("");
        //thanh toán
      //  Login l= new Login();
      //  l.returnma();
        String DateBuy=getdate();
        int gia=0;
        for(int i=0;i<table_chi_tiet_hd.getRowCount();i++)
        {
            gia+=Integer.parseInt(table_chi_tiet_hd.getValueAt(i, 4).toString());
        }
        
        quanlyhoadon hd=new quanlyhoadon(DateBuy,gia);
         // đồng thời lưu luôn chi tiết hóa đơn vào db
        if(a.AddHD(hd)>0){
              
             luu_db_chi_tiet_hd(a.getmahd());
              showTableHD();
        }
         
        
        JOptionPane.showMessageDialog(this, "Them hoa don thanh cong!");   
    }//GEN-LAST:event_btnThanh_toanActionPerformed

// xóa hóa đơn
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    selectedIndex=table_hd.getSelectedRow();
    quanlyhoadon sp= hoadon.get(selectedIndex);
    new HoaDonModify().DeleteHD(sp.getMahd());
    showTableHD();
    JOptionPane.showMessageDialog(this, "Xoa thanh cong");
    }//GEN-LAST:event_btnDeleteActionPerformed

//click chuột vào bảng hóa đơn    
    private void table_hdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_hdMouseClicked
        int numRow=table_hd.getSelectedRow();
       int ma_hd=Integer.parseInt(table_hd.getValueAt(numRow, 0).toString());
        
       System.out.println(ma_hd);
     chi_tiet_hd sp=sanphamct.get(ma_hd);
        
     //  dao.getchi_tiet_hdByMa_hd(ma_hd); 
        System.out.println(dao.getchi_tiet_hdByMa_hd(ma_hd));
        showTableSPCT();
        
    }//GEN-LAST:event_table_hdMouseClicked
// xóa sản phẩm khỏi giỏ hàng
    private void btnXoa_gioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa_gioActionPerformed
        selectedIndex=table_chi_tiet_hd.getSelectedRow();
        chi_tiet_hd sp=sanphamct.get(selectedIndex);
        sanphamct.remove(selectedIndex);
        showTableSPCT_tamthoi();
    }//GEN-LAST:event_btnXoa_gioActionPerformed
// tìm kiếm hóa đơn
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(txt_sdt_khach.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "!!! Chưa nhập sdt khách hàng cần tìm hóa đơn");
        }else{           
                hoadon=new HoaDonModify().getHoa_donBySdt(txt_sdt_khach.getText());
                ModelHD.setRowCount(0);
                hoadon.forEach((quanlyhoadon)->{
                    ModelHD.addRow(new Object[]{quanlyhoadon.getMahd(),quanlyhoadon.getSdt_kh(),quanlyhoadon.getDate_Buy(),quanlyhoadon.getThanhTien()});
                });
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hoadon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd_bill;
    private javax.swing.JButton btnAdd_sp;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnThanh_toan;
    private javax.swing.JButton btnXoa_gio;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_chi_tiet_hd;
    private javax.swing.JTable table_hd;
    private javax.swing.JTable table_sanpham;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtSo_luong;
    private javax.swing.JTextField txtSp;
    private javax.swing.JTextField txtTensp;
    private javax.swing.JTextField txtTong;
    private javax.swing.JTextField txt_sdt_khach;
    // End of variables declaration//GEN-END:variables
}
